### ISSUE TITLE
CS++DSCContent.vi is missing two classes

### ISSUE THREAD

**Issue by HB-BNT** [HB-GSI/CSPP_DSC#1]
Currently using branch: HBDev

- CS++DSCMonitor.lvlib:CS++DSCMonitor.lvclass
- CS++DSCConnection.lvlib:DSCConnection.lvclass

**Comment by HB-GSI** [comment]
CS++DSCConnection.lvlib:DSCConnection.lvclass and CS++DSCManager.lvlib:CS++DSCManager.lvclass added.
